# Generated by Django 3.1.7 on 2021-03-10 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=120)),
                ('degree', models.CharField(max_length=120)),
                ('yearOfGraduation', models.CharField(max_length=120)),
                ('groupNumber', models.CharField(max_length=120)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation', to='alumni.alumni')),
            ],
        ),
        migrations.CreateModel(
            name='GraduationProject',
            fields=[
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('gitLink', models.CharField(max_length=120)),
                ('graduation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='projects', serialize=False, to='alumni.graduation')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=120)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='alumni.alumni')),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='job', to='alumni.company')),
            ],
        ),
    ]
