# Generated by Django 3.1.7 on 2021-03-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='graduationproject',
            name='graduation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='grad_project', serialize=False, to='alumni.graduation'),
        ),
        migrations.AlterField(
            model_name='job',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='alumni.alumni'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='company', to='alumni.company'),
        ),
    ]
