# Generated by Django 3.1.7 on 2021-03-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20210323_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='current_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
