# Generated by Django 3.1.7 on 2021-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20210326_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='current_job',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='skype_link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
