# Generated by Django 3.1.7 on 2021-03-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_graduation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduation',
            name='university',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
